package com.zhou.test.drools.clock
import com.zhou.test.drools.Clock

rule "run"
    salience 1
    when
        c: Clock(!(minute == 60 && second == 60))
    then
        System.out.println(c+" #rule1");
        Thread.sleep(1000);
        c.setSecond(c.getSecond() + 1);
        update(c);
end

rule "second"
    salience 2
    when
        c: Clock(second == 60);
    then
        System.out.println(c+" #rule2");
        c.setMinute(c.getMinute() + 1);
        c.setSecond(0);
        update(c);
end

rule "minute"
    salience 3
    when
        c: Clock(minute == 60)
    then
        c.setHour(c.getHour() + 1);
        c.setMinute(0);
        update(c);
end